application: diggen-annons-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true


builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /upgrade
  script: upgrade1.py
  login: admin

- url: /ads/.*/admin
  script: admin.py
  login: admin

- url: /billboards/.*/admin
  script: admin.py
  login: admin

- url: .*
 script: main.py
 """ 
  script: diggen-annons-hrd.app
"""